apiVersion: v1
kind: Service
metadata:
  name: kubecracker-vm-1
spec:
  selector:
    app: kubecracker-vm-1
  type: LoadBalancer
  ports:
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: 22
    - name: runner
      protocol: TCP
      port: 9876
      targetPort: 9876
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000