name: Build

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build-rootfs-builder:
    name: Build rootfs builder
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./images/rootfs/builder
        tags: anyfiddle/firecracker-rootfs-builder:latest
        push: true

  build-ubuntu-docker-image:
    name: Build ubuntu docker image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./images/rootfs/ubuntu-docker
        tags: anyfiddle/firecracker-ubuntu-rootfs:latest
        push: true

  build-ubuntu-docker-rootfs:
    name: Build ubuntu docker rootfs
    runs-on: ubuntu-latest
    container: 
      image: anyfiddle/firecracker-rootfs-builder:latest
      options: "--entrypoint /bin/sh"
    steps:
    - uses: actions/checkout@v2
    - shell: sh
      run: |
        ls
        ./create-rootfs.sh anyfiddle/firecracker-ubuntu-rootfs:latest
