name: Build Rootfs

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  build:
    name: Build FIND image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: docker_meta
      name: Docker add meta data
      uses: crazy-max/ghaction-docker-meta@v1
      with:
        images: anyfiddle/find
    - uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        tags: ${{ steps.docker_meta.outputs.tags }}
        push: true
